export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const CONFIRM_INVITATION_REQUEST = 'CONFIRM_INVITATION_REQUEST';
